name: Get module names and tags

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "The git tag of the module to publish."
        required: true
        type: string

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install packages
        run: npm ci

      - name: Get module names and tags
        uses: actions/github-script@v6
        with:
          result-encoding: string
          script: |
            const script = require("./scripts/github-actions/get-module-names-with-tags.js")
            await script({ require, core })
